### ISSUE TITLE
笑死我了

### ISSUE THREAD

**Issue by 1mogude1** [Mosney/anti-anti-AD#1]
看到你这repo还以为anti-ad出啥事了，都准备把anti-ad移除了，仔细一看居然是关于轮子，那他可做的太棒了。反对邪教可2从来不是什么私人因素

**Comment by KyonCN** [comment]
目前翻防火墙的star最多的一键脚本也屏蔽轮子，建议maintainer再开个repo来anti一下

**Comment by Mosney** [comment]
> 目前翻防火墙的star最多的一键脚本也屏蔽轮子，建议maintainer再开个repo来anti一下

请问这二者之间有什么逻辑关系么？
