### ISSUE TITLE
你可真搞笑，截图不截全，想看轮子自己看

### ISSUE THREAD

**Issue by lyfhlz** [Mosney/anti-anti-AD#2]
<img width="672" alt="a" src="https://user-images.githubusercontent.com/57335239/87243115-cd1a1100-c465-11ea-955c-b4b0311bf11e.png">

**Comment by Mosney** [comment]
眼睛不需要请捐给有妈的人
> ![Screenshot_20200713-002406](https://user-images.githubusercontent.com/22477230/87251580-484be900-c49f-11ea-8f7c-1aa413e088a3.jpg)
